### ISSUE TITLE
Undefined name 'execute' in ip-osint.py

### ISSUE THREAD

**Issue by cclauss** [j3ssie/IPOsint#5]
Is this a missing import?  https://github.com/j3ssie/IPOsint/search?q=execute&unscoped_q=execute

[flake8](http://flake8.pycqa.org) testing of https://github.com/j3ssie/IPOsint on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./ip-osint.py:117:2: F821 undefined name 'execute'
	execute.run1('git fetch --all && git reset --hard origin/master')
 ^
1     F821 undefined name 'execute'
1
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by j3ssie** [comment]
it should be fixed now.
My shame for copy code from my another project :D
